"""Reader-facing copy for every stage recorded in the app trace.

The model transcript and the UI trace are different contracts. Model prompts may
contain operating and safety instructions; a trace stage carries only a compact
description of the work, concrete tool I/O, and the outcome a reader can act on.
"""

from __future__ import annotations

import re

DATA_SOURCE_FINDER_TASK = "Identify the governed data available for this question."

TOOL_STAGE_NAMES = {
    "data_genie": "Queried governed data",
    "dictionary_genie": "Checked field definitions",
    "list_data_assets": "Listed available tables",
    "search_tagged_assets": "Searched catalog tags",
    "resolve_table": "Located the named table",
    "describe_table": "Read a table's columns",
    "query_named_table": "Queried the named table",
    "run_sql": "Ran a governed read-only query",
}

TOOL_STAGE_RUNNING = {
    "data_genie": "Querying governed data",
    "dictionary_genie": "Checking field definitions",
    "list_data_assets": "Listing available tables",
    "search_tagged_assets": "Searching catalog tags",
    "resolve_table": "Locating the named table",
    "describe_table": "Reading a table's columns",
    "query_named_table": "Querying the named table",
    "run_sql": "Running a governed read-only query",
}

_TOOL_STAGE_ID = re.compile(r"^step-\d+-\d+-(?P<tool>.+)$")
_MODEL_STEP_ID = re.compile(r"^step-\d+$")
_TOOL_OUTPUT_NOTES = (
    "Asked together with the other definition questions in this step,",
    "Already asked in this run.",
)
_ERROR_INSTRUCTION_MARKERS = (
    ". Do not ",
    ". Do NOT ",
    ". Report this ",
    ". Call ",
    ". Ask ",
    ". Answer ",
    ". This is an outage",
)


def tool_name_from_stage_id(stage_id: str) -> str:
    """The callable name encoded in a tool stage id, if present."""

    match = _TOOL_STAGE_ID.fullmatch(stage_id)
    return match.group("tool") if match else ""


def _project_semantic_output(value: str) -> str:
    if value.startswith("SEMANTIC SEARCH UNAVAILABLE"):
        return value.split(" This is discovery, not data", 1)[0].strip()

    kept: list[str] = []
    for paragraph in value.split("\n\n"):
        item = paragraph.strip()
        if not item or item.startswith("SEMANTIC SEARCH RESULTS."):
            continue
        if item.startswith("What appears above was filtered by a cached snapshot"):
            continue
        if item.startswith("No semantic entries matched."):
            kept.append("No semantic entries matched.")
            continue
        if " Search again with a narrower question" in item:
            item = item.split(" Search again with a narrower question", 1)[0].strip()
        kept.append(item)
    return "\n\n".join(kept)


def _project_named_tool_output(value: str, tool: str) -> str:
    if tool == "search_semantics":
        return _project_semantic_output(value)
    if tool == "list_data_assets":
        return "\n".join(
            line for line in value.splitlines() if not line.startswith("Access note:")
        ).strip()
    if tool == "search_tagged_assets":
        if value.startswith("TAG SEARCH UNAVAILABLE"):
            return value.split(" This is discovery, not data", 1)[0].strip()
        return value.split(" Use list_data_assets", 1)[0].strip()
    if tool == "resolve_table" and value.startswith("AMBIGUOUS:"):
        heading, _, remainder = value.partition(". Do not ")
        listed = remainder.partition(":\n")[2]
        return f"{heading}.\n{listed}".strip()
    if tool == "describe_table":
        for marker in (". Call resolve_table", ". That is definitive:"):
            if marker in value:
                return value.split(marker, 1)[0].strip() + "."
    if tool == "dictionary_genie" and "Definition note:" in value:
        lines = []
        for line in value.splitlines():
            if line.startswith("Definition note:"):
                lines.append(
                    "The dictionary space answered without reading the dictionary table; "
                    "this is the space's account, not a governed entry."
                )
            else:
                lines.append(line)
        return "\n".join(lines).strip()
    return value


def project_tool_output(text: str, tool: str = "") -> str:
    """Remove agent-only guidance from a recorded tool result.

    Ordinary successful tool output is byte-for-byte unchanged. Only envelopes
    generated by this runtime are shortened, so user prose and returned data are
    never rewritten because they happen to contain words such as "must" or
    "never".
    """

    value = (text or "").strip()
    if not value:
        return ""
    if value.startswith(_TOOL_OUTPUT_NOTES):
        return value.split("\n\n", 1)[1].strip() if "\n\n" in value else ""
    if value.startswith("REFUSED:"):
        return value.split("\n\n", 1)[0].strip()
    if value.startswith("ERROR:"):
        first = value.split("\n\n", 1)[0].strip()
        cut = len(first)
        for marker in _ERROR_INSTRUCTION_MARKERS:
            at = first.find(marker)
            if at >= 0:
                cut = min(cut, at + 1)
        return first[:cut].strip()
    return _project_named_tool_output(text, tool)


def project_stage_input(stage_id: str, kind: str, text: str) -> str:
    """The compact task input allowed into live and stored traces."""

    if stage_id == "data_source_finder":
        return DATA_SOURCE_FINDER_TASK
    if stage_id == "attachment":
        return "Include the bounded attachment context supplied with this question."
    if stage_id == "synthesis":
        return "Prepare the final answer from assessed findings."
    if _MODEL_STEP_ID.fullmatch(stage_id):
        return "Choose the next governed data operation for this question."
    # The run envelope is the one stage whose input is ordinary user prose. Tool
    # arguments are also part of the explicit trace contract.
    return text


def project_stage_output(stage_id: str, kind: str, text: str, status: str) -> str:
    """The compact result allowed into live and stored traces."""

    if stage_id == "data_source_finder":
        if status == "failed":
            return "Governed data discovery could not complete."
        if status == "partial":
            return "Governed data discovery ended with unresolved gaps."
        if "## DATA OVERVIEW" in text:
            return "Identified the governed data available for this question."
        return "Prepared an assessed data package from governed sources."
    if stage_id == "attachment":
        return "Bounded attachment context was available to this run."
    if _MODEL_STEP_ID.fullmatch(stage_id):
        calls = [item.strip() for item in text.split(",") if item.strip()]
        if (
            calls
            and len(calls) == len(text.split(","))
            and all(re.fullmatch(r"[a-z_][a-z0-9_]*", item) for item in calls)
        ):
            return ", ".join(calls)
        if status == "failed":
            return "The reasoning step did not complete."
        return "Prepared assessed findings from governed sources."
    tool = tool_name_from_stage_id(stage_id)
    if tool or stage_id == "inventory":
        return project_tool_output(text, tool or "list_data_assets")
    return text
