import type { TraceStage } from './answer-shape';

/*
 * `askElapsedLabel` has moved to working-animation.ts, split in two, and the
 * split is a correction rather than a tidy-up.
 *
 * It returned one string, "Working on it \u2014 23s", which was wrong twice over
 * once the astrolabe copy rules landed. §3 and §7 forbid the em dash and make
 * the separator " \u00b7 ", and it was in live UI copy on the surface a reader
 * looks at for twenty seconds at a time. And the count has to be set in DM Mono
 * (`loading-suite.md`), which a caller cannot do to a substring of a string it
 * was handed without matching on the words. So the label is a constant and the
 * count is `elapsedSeconds`, and the separator is generated by `.ast-sep`.
 */

/**
 * The longest stage in a run, read off the run.
 */
export function slowestStageName(stages: TraceStage[]) {
  if (stages.length === 0) return null;
  return stages.reduce((slowest, stage) => (stage.duration > slowest.duration ? stage : slowest)).name;
}
